services:
  - type: web
    name: darse-burhani
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true

